// Field order: https://github.com/acmi/xdat_editor_schema/tree/master/src/main/groovy/ct0
using System.Collections.Generic;
namespace LocalL2Keys { internal static class XdatSchema {
internal static readonly Dictionary<string,string> Fields = new Dictionary<string,string> {
    {"BarCtrl", "s:foreTexture s:backTexture i:uSize i:vSize"},
    {"Button", "s:normalTex s:pushedTex s:highlightTex s:dropTex i:buttonName i:noHighlight i:defaultSoundOn i:disableTime"},
    {"ChatWindow", "i:lineGap"},
    {"CheckBox", "i:titleIndex i:checked i:leftAligned i:maxWidth s:checkTexture s:unCheckTexture s:disableTexture s:disableCheckTexture"},
    {"ComboBox", "@ComboBoxElement:values"},
    {"ComboBoxElement", "i:sysString i:systemMsg s:text i:reserved"},
    {"EditBox", "i:type i:maxLength i:showCursor i:chatMarkOn"},
    {"EffectButton", "i:type s:normalTex s:pushedTex s:highlightTex s:effectTex1 s:effectTex2"},
    {"FishViewportWindow", "s:texBack s:texClock s:texFishHPBar s:texFishHPBarBack s:texFishFakeHPBarWarning s:texFishingEffect s:texIconPumping s:texIconReeling"},
    {"HtmlCtrl", "s:viewType"},
    {"InvenWeight", ""},
    {"ItemWindow", "i:col i:row i:maxItemNum i:iconWidth i:iconHeight i:gapX i:gapY i:offsetX i:offsetY i:backgroundItemWidth i:backgroundItemHeight s:backgroundItemTex i:selectedItemWidth i:selectedItemHeight s:selectedItemTex i:unselectedItemWidth i:unselectedItemHeight s:unselectedItemTex i:noSelectItem i:noItemDrag i:buttonClick i:useCoolTime i:noScroll s:outLineUp s:outLineDown"},
    {"ListCtrl", "i:unk100 i:unk101 i:unk102 i:unk103 i:unk104 @ListElement:values"},
    {"ListElement", "i:textStringId i:width i:unk108 i:unk109 i:unk110"},
    {"MinimapCtrl", "i:showTime i:showTown i:showGrid i:showMyLocMark i:showMyLocText i:showSSQText"},
    {"MultiEdit", "i:unk100 i:unk101"},
    {"MultiSellItemInfo", ""},
    {"MultiSellNeededItem", ""},
    {"NameCtrl", ""},
    {"Progress", "s:backTexture s:barTexture i:gap"},
    {"Radar", ""},
    {"RadioButton", "i:sysstring i:radioGroupID i:isChecked"},
    {"ScrollArea", "i:areaHeight @DefaultProperty:children"},
    {"Shortcut", "s:unk0 s:unk1 @Action:actions"},
    {"Action", "i:key_1 i:key_2 i:key_3 s:action"},
    {"ShortcutItemWindow", "i:alwaysShowOutline"},
    {"SliderCtrl", "i:numOfTick i:currTick i:thumbBtnWidth i:thumbBtnHeight s:backTexture s:disableBackTexture s:thumbBtnNormalTexture s:thumbBtnDownTexture i:pushBtnWidth i:pushBtnHeight i:pushBtnAutoHitTime i:unk111 s:tickTexture"},
    {"StatusBar", "s:title i:textureWidth i:textureHeight s:foreTexture s:backTexture s:warnTexture s:regenTexture"},
    {"StatusIconCtrl", "i:noClip i:noTooltip"},
    {"Tab", "@TabElement:tabs"},
    {"TabElement", "i:buttonName s:target i:width i:height s:normalTex s:pushedTex i:movable i:gap i:tooltip i:noHighlight"},
    {"TextBox", "s:text i:textAlign i:offsetY s:backTex i:fontType i:sysstring i:systemMsg i:textColor i:emoticon i:autosize"},
    {"TextListBox", "i:maxRow i:showRow i:lineGap i:isShowScroll"},
    {"Texture", "s:file i:type i:layer i:u i:v i:uSize i:vSize i:alpha i:isAnimTex"},
    {"TreeCtrl", "i:saveExpandedNode i:multiExpand"},
    {"Window", "s:unk100 s:unk101 s:unk102 s:unk103 i:unk104 i:unk105 i:unk106 i:unk107 i:unk108 i:unk109 i:unk110 i:unk111 i:unk112 i:unk113 i:unk114 i:unk115 i:unk116 i:unk117 i:unk118 i:unk119 i:unk120 i:unk121 i:unk122 i:unk123 i:unk124 i:unk125 i:unk126 i:unk127 i:unk128 s:unk129 i:unk130 i:unk131 i:unk132 i:unk133 i:unk134 i:unk135 s:unk136 i:unk137 i:unk138 s:unk139 @DefaultProperty:children"},
    {"WndDefPos", "s:wnd i:alignment i:x i:y i:moveParent i:width i:height"},
}; } }
